name: Generate Snake Game

on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"

  # Permite executar manualmente a qualquer momento
  workflow_dispatch:

  # Executa a cada push na branch main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Gera o Snake Game a partir do gráfico de contribuições do GitHub
      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Alessandragr  # Substitua pelo seu nome de usuário
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Faz push do arquivo SVG gerado para o branch 'output'
      - name: Push Snake Game to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
