name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Alessandragr
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif  # Adicione isso para gerar um GIF também

      # Cria o branch 'output' se ele não existir
      - name: Create output branch
        run: |
          git checkout --orphan output
          git reset --hard
          git commit --allow-empty -m "Initial commit"
          git push origin output

      # Publica no GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
