name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: Alessandragr
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: "#6e5494"  # Cor da cobrinha (roxo)
          color_dots: "#c6c6c6"   # Cor dos pontos (cinza claro)
          color_bg: "transparent" # Fundo transparente

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
